### ISSUE TITLE
Can't install skyrim the phoenix flavor because steam is installed in multiple locations

### ISSUE THREAD

**Issue by detharize** [Codygits/TPF-Updates#1]
Trying to install the Phoenix flavour mod for skyrim but get a popup that it can't find Skyrim.

When I look at the wabbajack error log, I see an error that says "Outside of standard install folder, not updating.  
79.61 - Could not locate Skyrim Special Edition

79.61 - Exiting because we couldn't find the game folder.

I have steam games installed on three separate drives.
My primary steam directory is e:\games\steam\steamapps\common
Skyrim V is installed on F:\games\steam\steamapps\common\skyrim special edition
Then I have a few games installed on a G drive which is an ssd.

Would it work if I move skyrim to the e: drive, or is it because I have steam games under a \games\ directory or is it some other issue?
I haven't tried moving it because my e drive is full and I would have to delete or move some games to make room for skyrim.

**Comment by Codygits** [comment]
Would probably be best to show the logs in The Phoenix Flavour discord and get it sorted out there.
