### ISSUE TITLE
Unneeded record in TPF Conflict Patch

### ISSUE THREAD

**Issue by tohuw** [Codygits/TPF-Updates#3]
A minor nit, but the record for the placed object `FF742` in Worldspace `91F4` is just a forward of the same record in LoS II, which is already the conflict winner.

**Comment by tohuw** [comment]
Same for `FF73C` in `9278`

**Comment by tohuw** [comment]
`FF736` in `929B` also

**Comment by tohuw** [comment]
`F5D87` in `92E1` is *almost* the same way, but it adds light data (XLIG). I don't know if that's intentional or a holdover from Relighting Skyrim, though.

**Comment by Codygits** [comment]
Removed records from the CRP, thanks :)
