### ISSUE TITLE
Half of a fullscreen when enabled

### ISSUE THREAD

**Issue by VladAdGad** [Codygits/TPF-Updates#4]
Hi. With and without widescreen options I see only half of full screen and cannot change the resolution. 
I followed the instruction as you mentioned and run the game using skse in MO2 "Run".
I searched in profiles for some settings but no luck
![photo_2022-09-27_22-33-13](https://user-images.githubusercontent.com/15636176/192649388-2cf79031-431e-406e-9202-fa3f072c23a0.jpg)

**Comment by sorenvalen** [comment]
is windows scaling setting set to 100 or default i had this issue a few months ago with another list

**Comment by VladAdGad** [comment]
> is windows scaling setting set to 100 or default i had this issue a few months ago with another list

that was an issue, thank you
